family: PERSONNEL SECURITY
documentation_complete: false
satisfies:
- control_key: PS-1
  control_name: PERSONNEL SECURITY POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The {{project.name_short}} documents the security policy and procedures
      in addressing position categorization, personnel screening, personnel
      termination, personnel transfer, and access agreements within the
      {{project.name_short}} SSP. {{project.name_short}} adopts the
      {{project.client_name_short}} personnel security standards and determines
      position risks levels based on public trust responsibilities.


      This is Agency common control. More data about implementation can be
      obtained from the Agency common control catalog.
  implementation_status: {{responsibility.PS_1.project}}
- control_key: PS-2
  control_name: POSITION RISK DESIGNATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      {{project.name_short}} position sensitivity levels are assigned by the
      {{project.client_name}}. Each position designation is documented on the
      Standard Position Description (SPD) and assigned a risk level (or
      sensitivity level) commensurate with the sensitivity of the information,
      the risk to that information and the system maintaining that information.
      The levels of risk still need to be designated by
      {{project.client_name_short}} for employee and contractor positions but
      since {{project.name_short}} system does not have any sensitive data,
      a low risk scenario can be assumed.


      - Employee risk levels and background investigations are: Low Risk= NACI, Moderate Risk= LBI,
        High Risk= BI.

      - Contractor risk levels and background investigations are: Low Risk= NACI, Moderate Risk= NACC,
        High Risk= BI.


      In order to ensure every employee is assigned to a position, which has
      been reviewed for sensitivity by the NCC, the SPD is a required data
      attribute of an employee’s HR record. Position risks designations are
      reviewed and revised when NCC or OPM publish changes to sensitivity
      levels.


      This is Agency common control. More data about implementation can be
      obtained from the Agency common control catalog
  implementation_status: {{responsibility.PS_2.project}}
- control_key: PS-3
  control_name: PERSONNEL SCREENING
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      Minimum background investigations are conducted, since all data is
      non-sensitive, for individuals requiring access to {{project.name_short}}
      information and information systems. The type of background investigation
      conducted for an individual is determined by the individual’s position
      risk categorization noted in control PS-2. {{project.client_name_short}}
      conducts periodic reinvestigations in accordance with OPM and NIST
      guidelines.


      This is Agency common control. More data about implementation can be
      obtained from the Agency common control catalog.
  implementation_status: {{responsibility.PS_3.project}}
- control_key: PS-4
  control_name: PERSONNEL TERMINATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      {{project.client_name}} HR policy states that managers or designated
      officials are responsible for recovering and properly securing employee
      badges and returning it to the local physical security office. The
      {{project.client_name_short}} executes termination procedures that remove
      personnel access privileges, computer accounts. When an employee is
      terminated, the employee’s manager or designated official completes a
      form requesting termination of access for the user. Local management and
      the security manager coordinate disabling or removing {{project.name_short}}
      privileged access with the system administrator. The employee’s manager
      or designated official is responsible for recovering and properly
      securing his/her ID badge and returning it to the local physical security
      office. The employee’s manager or designated official ensures that any
      information on the system that the employee was responsible for will be
      available to the appropriate personnel.


      This is Agency common control. More data about implementation can be
      obtained from the Agency common control catalog.
  implementation_status: {{responsibility.PS_4.project}}
- control_key: PS-5
  control_name: PERSONNEL TRANSFER
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      When an employee is reassigned or transferred, the employee’s manager or
      designated official is required to request transfer of access (as
      appropriate) for the user.


      In accordance with the {{project.client_name}} HR policy, the employee’s
      manager or designated official is responsible for recovering and properly
      securing his/her ID badge and returning it to the local physical security
      office. The manager provides prompt notification to the
      {{project.name_short}} system/security administrator when an employee
      changes assignments and/or location. This includes taking prompt and
      appropriate action to change employee access profile and/or remove
      employee from the system; and ensure that users’ system access is
      cancelled when the need no longer exists.


      This is Agency common control. More data about implementation can be
      obtained from the Agency common control catalog.
  implementation_status: {{responsibility.PS_5.project}}
- control_key: PS-6
  control_name: ACCESS AGREEMENTS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      All users of the {{project.name_short}} system must read and accept
      access agreements upon every login.
  - key: b
    text: >
      The Access Agreements are reviewed at least annually or when a significant
      change occurs.
  - key: c
    text: >
      All individuals requiring access to the {{project.name_short}} system are
      required to sign the Access Agreements before login is granted. When the
      Access Agreements are updated, the individual will be required to sign
      the new copy before regaining access.
  implementation_status: {{responsibility.PS_6.project}}
- control_key: PS-7
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      Personnel security requirements including security roles and
      responsibilities that apply to primary contracting organizations flow down
      to their subcontractors.
  - key: b
    text: >
      Personnel security policies and procedures that apply to primary
      contracting organizations flow down to their subcontractors.
  - key: c
    text: >
      All personnel security requirements are documented in PS-1 and other
      related Personnel Security controls.
  - key: d
    text: >
      For personnel transfers and terminations of third-party personnel, the
      procedures defined in employee termination (PS-4) and employee transfer
      (PS-5) flow down to subcontractors.
  - key: e
    text: >
      Compliance measures for assessing third-party personnel and/or contractors
      are determined on a case-by-case basis. Third-party personnel are
      monitored to ensure compliance with personnel security requirements.
  implementation_status: {{responsibility.PS_7.project}}
- control_key: PS-8
  control_name: PERSONNEL SANCTIONS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The disciplinary sanctions for personnel failing to comply with establish
      IT security policies and procedures are included in
      {{project.client_name}} HR policy. If an employee violates the
      {{project.client_name_short}} information security policies and procedures,
      the employee may be subject to disciplinary action at the discretion of
      management. Actions may range from verbal or written warning, removal of
      system access for a specific period of time, reassignment to other duties,
      or termination, depending on the severity of the violation. Disciplinary sanctions are reported to
      the OCIO.
  implementation_status: {{responsibility.PS_8.project}}
