---
system_security_plan:
  title: System Security Plan (SSP) Low Baseline
  date:
    _iso-date: iso-date3
    __text: '2019-11-20'
  upi: # Unique Project Identifier
certification:
  name: FISMA Low Impact
  abbr: fisma-low-impact
status: !include keys/responsibilty.yaml
poc: !include keys/poc.yaml
project: !include keys/project.yaml
artifact: !include keys/artifacts.yaml
contractor: !include keys/contractor.yaml
coop: !include keys/coop.yaml
information_system: !include keys/info_system.yaml
pia: !include keys/pia.yaml
risk: !include keys/risk.yaml
services: !include keys/services.yaml