version: '3'
services:
  secrender-cli:
    image: drydockcloud/ci-secrender
    volumes:
      - .:/src
      - .:/results
  compliancetools-cli:
    image: drydockcloud/ci-compliancetools
    user: $UID
    env_file:
      - .env
    volumes:
      - .:/src
