name: AWS
family: CONFIGURATION MANAGEMENT
documentation_complete: false
schema_version: 3.0.0
satisfies:

- control_key: CM-01
  control_key_part: ~
  control_name: CONFIGURATION MANAGEMENT POLICY AND PROCEDURES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud Service Providers dated 1 May 2013.

- control_key: CM-02
  control_key_part: ~
  control_name: BASELINE CONFIGURATION
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system therefore inherits server configuration aspects of this control from
    the FedRAMP Provisional ATO granted to the AWS Cloud dated 1 May 2013 for
    the following: baseline configuration for IaaS components.

    Hardware Baselines

    All hardware is maintained by AWS Cloud. The system therefore inherits
    hardware configuration aspects of this control from the FedRAMP Provisional ATO
    granted to the AWS Cloud dated 1 May 2013 for the following: baseline configuration.

    Server Configuration

    AWS maintains the baseline software configuration for the server components
    required to run the Drupal platform upon which the system is built.

- control_key: CM-02 (1)
  control_key_part: c
  control_name: REVIEWS AND UPDATES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud Service Providers dated 1 May 2013.

- control_key: CM-03 (2)
  control_key_part: ~
  control_name: TEST / VALIDATE / DOCUMENT CHANGES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Before deployment to production, the code in the master branch of the repository
    is deployed to a staging server hosted by AWS where it the code changes are
    reviewed again. After all code changes have been reviewed and tested on the staging
    server, the code release is presented to the CCB for approval before the code
    is tagged for release and deployed to the production server.

- control_key: CM-05
  control_key_part: ~
  control_name: ACCESS RESTRICTIONS FOR CHANGE
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud dated 1 May 2013 for the following: physical access restrictions
    with changes to LINCS. Development and staging environments is logged by default
    as part of the AWS Managed Cloud system.

- control_key: CM-05 (1)
  control_key_part: ~
  control_name: AUTOMATED ACCESS ENFORCEMENT / AUDITING
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud dated 1 May 2013 for the following:
    automated access enforcement / access.

- control_key: CM-05 (5)
  control_key_part: a
  control_name: LIMIT PRODUCTION / OPERATIONAL PRIVILEGES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    CivicActions personnel cannot modify hardware or firmware components because they have
    no physical access to the servers. Software changes can only be performed by CivicActions
    developers with Senior Developer or Team Leader roles as defined by AWS.

- control_key: CM-06
  control_key_part: a
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud dated 1 May 2013 for the following: configuration settings
    for the system software components for the security configuration management
    processes and tools.

- control_key: CM-06
  control_key_part: b
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: Partially in Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud dated 1 May 2013.

- control_key: CM-06
  control_key_part: c
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: Partially in Place
  narrative: >
    The system partially inherits this control from the FedRAMP Provisional ATO granted
    to the AWS Cloud dated 1 May 2013 for the following:  explicit operational
    requirements for AWS managed components.

- control_key: CM-07
  control_key_part: a
  control_name: LEAST FUNCTIONALITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Access from the internet to the application running on AWS Managed Cloud is
    permitted only on port 80 TCP (HTTP) and port 443 TCP (HTTPS) for Drupal,
    and on port 22 TCP (SSH) for the underlying web server. AWS has access to
    all open ports on all other computing nodes within AWS Managed Cloud to
    monitor internal-facing services.

- control_key: CM-07
  control_key_part: b
  control_name: LEAST FUNCTIONALITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system inherits this control from the FedRAMP Provisional ATO granted to the
    AWS Cloud dated 1 May 2013 for the following:  least functionality.

- control_key: CM-08
  control_key_part: ~
  control_name: INFORMATION SYSTEM COMPONENT INVENTORY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Platform Software

    lincs.ed.gov is hosted on the AWS platform. The system
    therefore inherits the platform software components of this control from the FedRAMP
    Provisional ATO granted to the AWS Cloud dated 1 May 2013 for the following: 
    information system component inventory.

- control_key: CM-08 (1)
  control_key_part: ~
  control_name: UPDATES DURING INSTALLATIONS / REMOVALS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Website content is backed up daily by the AWS Managed Cloud hosting system, which
    is configured to take daily database snapshots

    The system partially inherits this control from the FedRAMP Provisional ATO granted to
    the AWS Cloud dated 1 May 2013 for the following: hardware components inventory
    updates.

- control_key: CM-10
  control_key_part: a
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    lincs.ed.gov is hosted on a LAMP platform (Linux, Apache, MySQL and PHP) that
    is managed by AWS. The system therefore inherits the platform software components
    of this control from the FedRAMP Provisional ATO granted to the AWS Cloud dated
    1 May 2013 for the following:  software usage restrictions (CM-10).

- control_key: CM-10
  control_key_part: b
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The system therefore inherits the platform software components of this control
    from the FedRAMP Provisional ATO granted to the AWS Cloud dated 1 May 2013
    for the following:  software usage restrictions (CM-10).

- control_key: CM-11
  control_key_part: a
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    lincs.ed.gov is hosted on the AWS platform. The system
    therefore inherits the platform software components of this control from the FedRAMP
    Provisional ATO granted to the AWS Cloud dated 1 May 2013 for the following: 
    Governing installation of software by users

- control_key: CM-11
  control_key_part: b
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    lincs.ed.gov is hosted on the AWS platform. The system
    therefore inherits the platform software components of this control from the FedRAMP
    Provisional ATO granted to the AWS Cloud dated 1 May 2013 for the following: 
    Enforcing software installation policies.

- control_key: CM-11
  control_key_part: c
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    lincs.ed.gov is hosted on the AWS platform. The system
    therefore inherits the platform software components of this control from the FedRAMP
    Provisional ATO granted to the AWS Cloud dated 1 May 2013 for the following: 
    Monitoring compliance.
