family: SECURITY
documentation_complete: false
satisfies:
- control_key: SE-1
  control_name: INVENTORY OF PERSONALLY IDENTIFIABLE INFORMATION
  standard_key: NIST SP 800-53 Revision 4 Privacy
  covered_by: []
  security_control_type: System Specific
  narrative:
  - text: |
      Example Org does not collect or maintain PII and therefore does not directly address this
      control though it may address it indirectly.
    implementation_status: Not Applicable
- control_key: SE-2
  control_name: PRIVACY INCIDENT RESPONSE
  standard_key: NIST SP 800-53 Revision 4 Privacy
  covered_by: []
  security_control_type: System Specific
  narrative:
  - text: |
      Example Org does not collect or maintain PII and therefore does not directly address this
      control though it may address it indirectly.
    implementation_status: Not Applicable
