name: LINCS
family: CONFIGURATION MANAGEMENT
documentation_complete: false
schema_version: 3.0.0
satisfies:

- control_key: CM-01
  control_key_part: ~
  control_name: CONFIGURATION MANAGEMENT POLICY AND PROCEDURES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The Department of Health and Human Service developed, documented and disseminated
    to personnel a configuration management policy  that addresses purpose, scope,
    roles, responsibilities, management committment, coordination among organizational
    entities, and compliance, and developed, documented and disseminated to personnel
    procedures to facilitate the implementation of the policy and associated controls.The
    policy is stated in the Office of the Secretary Information Security Policy dated
    July 17, 2013 and the procedures are defined in the Office of the Secretary Procedures
    Handbook for Information Security, Version 1.1 dated July 30, 2014. These documents
    will be reviewed periodically. These policies and procedures are applicable to
    the LINCS personnel using the lincs.ed.gov information system.

    The CivicActions ISSO is responsible for reviewing and updating the Configuration
    Management Policy and Procedures annually. All procedures are consistent with
    requirements of FISMA, FedRAMP, ISO 27001, applicable executive orders, directives,
    policies, regulations, standards, and guidance. These policies and procedures
    are applicable to the CivicActions staff administering the lincs.ed.gov information
    system. The DKAN SSP Configuration Management Plan can be found in the CivicActions
    HealthData GitHub repository wiki at
    <https://github.com/NuCivic/healthdata/wiki/configuration-management-plan>.

- control_key: CM-02
  control_key_part: ~
  control_name: BASELINE CONFIGURATION
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The application software component of lincs.ed.gov consists of (1) the DKAN
    distribution of the Drupal web application platform, with (2) additional software
    features that were developed expressly for lincs.ed.gov based on specifications
    provided by LINCS.

    Baseline configuration for the website's standard DKAN features is stored in the
    website's codebase and managed using the Features module for Drupal
    (<https://www.drupal.org/project/features>).
    Site administrators can view the list of features by visiting the site's features
    management page at https://www.lincs.ed.gov/admin/structure/features. Most of
    the configuration for additional features that were developed specifically for
    lincs.ed.gov is also managed using the Drupal Features module.

    The Features module makes it possible to override configuration for individual
    features without modifying the codebase. It stores those overridden features in
    the website's MySQL database. The features management page referenced above shows
    which components of each feature are based on the default configuration stored
    in code, and shows which components have been overridden in the database. Most
    components of lincs.ed.gov are based on the default configuration stored in
    code, but there are approximately a dozen components that have overrides stored
    in the database.

    CivicActions maintains documentation describing each custom feature for lincs.ed.gov
    that is not standard DKAN, as well as documentation describing feature components
    that have overrides stored in the database.

- control_key: CM-02
  control_key_part: ~
  control_name: BASELINE CONFIGURATION
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The baseline configuration is described in Section 3.2 of the Configuration Management
    Plan, which describes the approved configuration of the HDG system including all
    of its hardware, software, and firmware components and the physical and logical
    locations of each. In the context of Security Configuration Management, the baseline
    configuration is a collection of formally approved configuration state(s) of one
    or more configuration items ("features") that compose the HDG system. The baseline
    configuration is used by HDG to restore and serves as the basis against which
    the next change or set of changes to the HDG is made.

    The features for the HDG system are maintained in the website's source code, which
    is managed in git, a source code version control system. Once the source code
    is updated, git maintains the new version of staged code once committed in the
    git repository as the new baseline. All code prior to it being staged is documented,
    tested and approved by CivicActions' DKAN Engineering team, which is described
    in control SA-3. The HDG production environment is configured to take database
    snapshots daily.

- control_key: CM-02 (1)
  control_key_part: a
  control_name: REVIEWS AND UPDATES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    CivicActions reviews and updates baseline configurations for lincs.ed.gov at
    least annually, as an integral part of information system component installations,
    upgrades and maintenance.

- control_key: CM-02 (1)
  control_key_part: b
  control_name: REVIEWS AND UPDATES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Review of the CM baselines for the HDG system is conducted and approved by the
    DKAN Engineering team. Any changes made to the production environment are
    approved prior to deployment by the HDG CCB. Changes that may require updates
    to the baseline configuration for the lincs.ed.gov application include:

    • Significant upgrades or changes to applications or database software

    • Security assessment findings

    • Changes in internal/external security requirements

    • A new security threat, incident, or event

- control_key: CM-02 (2)
  control_key_part: ~
  control_name: AUTOMATION SUPPORT FOR ACCURACY / CURRENCY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    HDG configuration settings use automated mechanisms to automate code deployment
    and baseline settings changes. The website's baseline configuration may be reapplied
    to the site at any time by manually retriggering a code deployment using the AWS
    dashboard.

    The source code, which contains the site’s baseline configuration, is managed
    using git, a source code version control system. Git is used to track source code
    which allows administrators to easily deploy and roll back changes on production
    hosting environments.

    The Features module (described above under "Application Configuration") is used
    to export configuration settings from the website's MySQL database and stores
    them as code so that the configuration settings can be managed within the git
    source code version control system.

- control_key: CM-03
  control_key_part: g
  control_name: CONFIGURATION CHANGE CONTROL
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The Change Control Board (CCB) is a group containing two individuals (at a minimum)
    that have the collective responsibility and authority to review and approve proposed
    change to the HDG system. The LINCS OCIO Policy for Information Systems Security
    and Privacy Handbook requires that the configuration management process include
    the system CA (Certification Authority) or a representative from that system as
    a member of the CCB. The HDG CCB shall meet regularly at a time and place set
    by the HDG CCB Chair.  In addition, the HDG CCB Chair may convene the HDG CCB
    in an emergency session to address time-critical topics as deemed necessary.

- control_key: CM-06
  control_key_part: b
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: Partially in Place
  narrative: >
    Configuration settings are implemented, monitored, and controlled in accordance with the
    organizational Configuration Management Plan, section 2, for the security configuration
    management processes and tools.

- control_key: CM-06
  control_key_part: c
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: Partially in Place
  narrative: >
    Currently, deviations do not exist for established configuration settings. In
    the event this changes, the following notes the process that will take place.

    The CivicActions CCB, identifies, approves, and documents exceptions to mandatory
    configuration settings for individual components within its cloud offering only
    when operationally necessary.  All variances identified during the monthly and
    annual system testing scans that must be accepted for operational purposes are
    tracked.

- control_key: CM-08
  control_key_part: ~
  control_name: INFORMATION SYSTEM COMPONENT INVENTORY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Application software

    The software inventory for the lincs.ed.gov application is maintained in the
    codebase stored CivicActions' git source code version control system. It consists
    of the following components:

    • The Drupal open source web content management system

    • The DKAN distribution of Drupal

    • Drupal add-on modules, themes and libraries available from the Drupal.org website
    which extend Drupal core

    • Custom code written for lincs.ed.gov by CivicActions' developers

    The inventory is reviewed monthly by CivicActions' DKAN Product Engineering and
    Open Data Platform Engineering teams. In accordance with the HDG Configuration
    Management Plan, section 3.

- control_key: CM-09
  control_key_part: ~
  control_name: CONFIGURATION MANAGEMENT PLAN
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The HDG Configuration Management Plan addresses roles, responsibilities, and
    configuration management processes and procedures. It defines the configuration items
    for the information system and when in the system development life cycle the
    configuration items are placed under configuration management (section 3.1.1); and
    establishes the means for identifying configuration items throughout the system
    development life cycle (section 3.1.2) and a process for managing the configuration of
    the configuration items (section 4). This document can be found in the CivicActions
    HealthData GitHub repository at
    <https://github.com/NuCivic/healthdata/wiki/configuration-management-plan>.

- control_key: CM-10
  control_key_part: a
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The HDG system is built using CivicActions' DKAN distribution of Drupal which
    is licensed under the Free Software Foundation's General Public License (GPL),
    version 2 or later.

- control_key: CM-10
  control_key_part: b
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The HDG Configuration Management Plan, section 3.2.1., notes the software, function,
    and version for the software components of the HDG system. DKAN, Drupal core,
    and all third-party Drupal modules are licensed under the Free Software Foundation's
    General Public License (GPL), version 2 or later.

- control_key: CM-10
  control_key_part: c
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Not Applicable. Peer-to-peer and file sharing are not included in the authorization boundary.

- control_key: CM-11
  control_key_part: a
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    All software installed in the HDG system environment must be first approved via
    the CCB resulting in a Change Request (CR) being initiated and executed. No government-furnished
    equipment (GFE) is within the authorization boundary for the system. Software
    installation on the computing nodes within the authorization boundary is restricted
    to administrators. All CivicActions internal administrators are informed of this
    during their initial training and as part of the rules of behavior document.
