name: LINCS
family: PERSONNEL SECURITY
documentation_complete: false
schema_version: 3.0.0
satisfies:
- control_key: PS-01
  control_key_part: ~
  control_name: PERSONNEL SECURITY POLICY AND PROCEDURES
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    The Department of Health and Human Service developed, documented and disseminated
    to personnel a personnel security policy that addresses purpose, scope, roles,
    responsibilities, management committment, coordination among organizational entities,
    and compliance, and developed, documented and disseminated to personnel procedures
    to facilitate the implementation of the policy and associated controls.The policy
    is stated in the Office of the Secretary Information Security Policy dated July
    17, 2013 and the procedures are defined in the Office of the Secretary Procedures
    Handbook for Information Security, Version 1.1 dated July 30, 2014. These documents
    will be reviewed periodically. These policies and procedures are applicable to
    the LINCS personnel using the lincs.ed.gov information system.

    The CivicActions ISSO is responsible for reviewing and updating the Personnel Security
    Policy and Procedures annually. The Chief Operating Officer is responsible for
    approving Personnel Security.  All procedures are consistent with requirements of
    FISMA, FedRAMP, ISO 27001, applicable executive orders, directives, policies,
    regulations, standards, and guidance. These policies and procedures are applicable to
    the CivicActions staff administering the lincs.ed.gov information system.

- control_key: PS-06
  control_key_part: a
  control_name: ACCESS AGREEMENTS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    HDG users are required to read and sign access agreements, including acknowledgement
    signature page for the Acceptable Use Policy (AUP), provided in the Rules of Behavior
    (RoB) document prior to gaining access to the HDG. The acknowledgment signature page
    is a separate document provided within the referenced (RoB) document.

- control_key: PS-06
  control_key_part: b
  control_name: ACCESS AGREEMENTS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Access agreements, including the Acceptable Use Policy, are reviewed at least
    annually or when a significant change occurs. In the event that a major update
    is made to the Acceptable Use Policy, employees are required to read and sign
    the updated policy document and Human Resources stores the information.

- control_key: PS-06
  control_key_part: c
  control_name: ACCESS AGREEMENTS
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Prior to gaining access to key systems, HDG users are required to read
    and sign access agreements, including the Acceptable Use Policy.

    Access agreements, including the Acceptable Use Policy, are reviewed at least
    annually. This review also takes place when a significant change occurs. In the
    event that a major update is made to the Acceptable Use Policy, employees are
    required to meet with the Director of Human Resources to review and sign the revised
    agreement.

- control_key: PS-07
  control_key_part: a
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Third party personnel are required to following the same process and requirements as
    LINCS employees. The Chief Operating Officer may also require that a background check be
    conducted on contractors and / or third party users in cases where they will have
    access to application data that is not meant to be consumed by the public. In these
    instances, the Chief Operating Officer will instruct the Director of Human Resources
    to conduct a background check before granting access to the information system.

- control_key: PS-07
  control_key_part: b
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    LINCS HR reviews and updates the access agreements annually or whenever there is a
    significant change to the information system or information being processed; and
    whenever there is a change to the agreements’ verbiage.

- control_key: PS-07
  control_key_part: c
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    All personnel security requirements are documented within the SSP and include things
    such as signing the Acceptable Use Policy (AUP) and taking security awareness
    training.

- control_key: PS-07
  control_key_part: d
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    For personnel transfers and terminations of employees with access to the HDG systems,
    third parties must notify the LINCS Director of Human Resources the same day. The
    Director of Human Resources follows the same employee transfer and/or termination
    procedure(s) as if the Third Party Personnel were LINCS employees.

- control_key: PS-07
  control_key_part: e
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST-800-53
  covered_by: []
  security_control_type: Hybrid
  implementation_status: In Place
  narrative: >
    Compliance measures for assessing third-party personnel and/or contractors are
    determined on a case-by-case basis. The LINCS ISSO is responsible for coordinating
    with the Cloud Operations Manager and the Contracts Manager to include appropriate
    and tailored compliance verification language in contracts as required.  Third-party
    personnel are continuously monitored to ensure compliance with personnel security
    requirements.
