family: PERSONNEL SECURITY
documentation_complete: false
satisfies:
- control_key: PS-1
  control_name: PERSONNEL SECURITY POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      CivicActions has developed, documented and disseminated to personnel a personnel
      security policy that addresses purpose, scope, roles, responsibilities, management
      commitment, coordination among organizational entities, and compliance; and
      procedures to facilitate the implementation of the policy and associated controls.
      This information is maintained in CivicActions Personnel Security (PS) Policy
      document that can be found in the CivicActions Github repository at <https://github.com/CivicActions/compliance-docs>.
    implementation_status: In Place
- control_key: PS-2
  control_name: POSITION RISK DESIGNATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      Risk designations are assigned to all CivicActions positions. The CivicActions
      Director of Human Resources works in coordination with the CivicActions ISSO
      and the Chief Operating Officer to assign risk designations.
    implementation_status: In Place
  - key: b
    text: >
      The CivicActions Director of Human Resources works in coordination with the
      CivicActions ISSO and the Chief Operating Officer to establish screening criteria
      for all CivicActions positions.
    implementation_status: In Place
  - key: c
    text: >
      At least every three (3) years, the CivicActions Director of Human Resources
      reviews and revises position risk designations. If the Director of Human Resources
      determines that significant changes must be made to the position risk descriptions
      the Director of Human Resources works in coordination with the CivicActions
      ISSO and the Chief Operating Officer to implement changes as required.
    implementation_status: In Place
- control_key: PS-3
  control_name: PERSONNEL SCREENING
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      Prospective CivicActions employees undergo background checks commensurate with
      the individual’s job duties, the classification of the information they will
      access, and the risks associated with the role. At the discretion of the Chief
      Operating Officer these checks may also be conducted on contractors and / or
      third party users in cases where they will have access to application data that
      is not meant to be consumed by the public.  In these instances, the Chief Operating
      Officer will instruct the Director of Human Resources to conduct a background
      check before granting access to the information system.
    implementation_status: In Place
  - key: b
    text: >
      Rescreening is conducted as required by the individual’s job duties, the classification
      of the information they will access, and the risks associated with the role.
      A basic background check is performed for all CivicActions employees.
    implementation_status: In Place
- control_key: PS-4
  control_name: PERSONNEL TERMINATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      Information system access is terminated immediately upon the voluntary or involuntary
      departure of an employee. In the case of involuntary departure, in addition
      to immediate termination of system access, at no point is a departing employee
      allowed access to any part of the CivicActions infrastructure.

      In the case of voluntary departure, employees are permitted access to the information
      system for the duration of their off boarding period. The departing employee’s
      manager is responsible for informing the Information Technology department when
      the employee off boarding period concludes. At this time system and facility
      access is terminated.
    implementation_status: In Place
  - key: b
    text: |
      The terminated user’s accounts are disabled and all access associated with the individual is revoked.
    implementation_status: In Place
  - key: c
    text: >
      The employee's manager or the Director of Human Resources conducts exit interviews
      with all employees who leave CivicActions voluntarily. There is a general discussion
      about the process of turning in any/all company issued devices, laptops, etc.
    implementation_status: In Place
  - key: d
    text: >
      CivicActions employees provide their own equipment that must be hardened to
      security reqirements depending upon their role and duties. CivicActions supplies
      two factor authentication tokens that become the property of the employee.

      Some employees may receive company-issued hardware for working on poarticular
      projects. These items are collected before the employee exits CivicActions.  In
      the case of an involuntary termination, the Director of Human Resources works
      to collect company issued devices and provides paperwork highlighting confidential
      protections for customers.
    implementation_status: In Place
  - key: e
    text: >
      Access to CivicActions information and information systems is always shared,
      so that the termination of an individual will not prevent CivicActions from
      having access to needed resources.
    implementation_status: In Place
  - key: f
    text: >
      When a person is terminated, a standard off-boarding process is used to notify
      management and IT and to track the process of disabling access to the information
      system/information system components. CivicActions IT Operations and Security
      is given at least a four hour notice to schedule the deactivation of access
      upon termination. Deactivation is a manual process that is tracked via a Trello
      card in order to meet the four hour turnaround time before termination.
    implementation_status: In Place
- control_key: PS-5
  control_name: PERSONNEL TRANSFER
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      When an employee, third party personnel and / or contractor is transferred to
      a new project or position within CivicActions, they may maintain access to the
      previous system they were working on in order to facilitate the process of maintenance
      and knowledge transfer. However, as part of the practices of account management
      (AC-02) and least privilege (AC-06), regular audits of privileged users are
      conducted and access privileges may be removed when no longer needed. Additionally,
      adherence to specific client SLAs may enhance the frequency of such audits or
      the timeliness of privilege removal during personnel transfer.
    implementation_status: In Place
  - key: b
    text: >
      When an employee, third party personnel and / or contractor is transferred to
      a new position within CivicActions and there is a requirement for access change,
      such access changes are normally completed within five business days.
    implementation_status: In Place
  - key: c
    text: |
      Access authorizations are modified as needed to coincide with changes in duties or operational need upon personnel transfer or reassignment.
    implementation_status: In Place
  - key: d
    text: >
      CivicActions Operations is informed of transfers that require access authorization
      modifications within five business days by the Project Manager, System Owner
      or Director of Human Resources.
    implementation_status: In Place
- control_key: PS-6
  control_name: ACCESS AGREEMENTS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: |
      CivicActions has developed and documented an Acceptable Use Policy that covers access and use of all CivicActiuons systems.
    implementation_status: In Place
  - key: b
    text: >
      The Acceptable Use Policy is reviewed at least annually or when a significant
      change occurs. In the event that a major update is made to the Acceptable Use
      Policy, employees are required to read and sign the updated policy document
      and Human Resources stores the information.
    implementation_status: In Place
  - key: c
    text: >
      All CivicActions team members are required to read and sign the Acceptable Use
      Policy (AUP) provided in the Security Policy document prior to gaining access
      to the any CivicActions system. The acknowledgment signature page is a separate
      document collected and recorded by the Director of Human Resources.
    implementation_status: In Place
- control_key: PS-7
  control_name: THIRD-PARTY PERSONNEL SECURITY
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: |
      Third party personnel are required to following the same process and requirements as CivicActions employees.
    implementation_status: In Place
  - key: b
    text: >
      Third party personnel are required to following the same process and requirements
      as CivicActions employees. CivicActions Operations or Security may require that
      a background check be conducted on contractors and / or third party users in
      cases where they will have access to application data that is not meant to be
      consumed by the public.
    implementation_status: In Place
  - key: c
    text: >
      All personnel security requirements are documented and include things such as
      signing the Acceptable Use Policy (AUP) and taking security awareness training.
    implementation_status: In Place
  - key: d
    text: >
      For personnel transfers and terminations of third-party personnel with access
      to the CivicActions systems, third parties must notify the CivicActions Operations
      an/or Director of Human Resources the same day. The same employee transfer and/or
      termination procedure(s) are folloed as if the third party personnel were CivicActions
      employees.
    implementation_status: In Place
  - key: e
    text: >
      Compliance measures for assessing third-party personnel and/or contractors are
      determined on a case-by-case basis. CivicActions Security is responsible for
      coordinating with the managers of external systems to include appropriate and
      tailored compliance verification language in contracts as required.  Third-party
      personnel are continuously monitored to ensure compliance with personnel security
      requirements.
    implementation_status: In Place
- control_key: PS-8
  control_name: PERSONNEL SANCTIONS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      The Director of Human Resources is responsible for determining and enforcing
      sanctions for failing to comply with established information security policies
      and procedures. Coaching may be considered prior to sanctions. Sanctions may
      include but are not limited to written warnings, reduction in system access,
      demotion, or termination.
    implementation_status: In Place
  - key: b
    text: >
      When employee sanctions processes are initiated, the Director of Human Resources
      notifies the respective Project Manager(s) and CivicActions Security within
      five business days.
    implementation_status: In Place
