family: PERSONNEL SECURITY
documentation_complete: false
satisfies:
- control_key: PS-1
  control_name: PERSONNEL SECURITY POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: |
      The system partially inherits this control from the FedRAMP Provisional ATO granted to the AWS Cloud Service Provider dated 1 May 2013.
    implementation_status: In Place
