family: CONFIGURATION MANAGEMENT
documentation_complete: false
satisfies:
- control_key: CM-1
  control_name: CONFIGURATION MANAGEMENT POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      {{contractor.name_short}} has developed, documented and disseminated to
      personnel a configuration management policy that addresses purpose,
      scope, roles, responsibilities, management commitment, coordination among
      organizational entities, and compliance; and procedures to facilitate the
      implementation of the policy and associated controls. This information is
      maintained in the {{contractor.name_short}} Configuration Management (CM)
      Policy. This document can be found in the {{contractor.name_short}}
      Compliance Docs GitHub repository at <{{contractor.compliance_docs_url}}>.

      Configuration changes are overseen by the Change Control Board (CCB)
      consisting of the System Owner, Project Manager, {{contractor.name_short}}
      Operations staff and the engineering team.
  implementation_status: {{status.CM_1.contractor}}
- control_key: CM-2
  control_name: BASELINE CONFIGURATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      A current baseline configuration is always available - stored as a tag in
      the Git repository - such that the site can be regenerated or rolled back
      should unauthorized or failing changes be applied.
  implementation_status: {{status.CM_2.contractor}}
- control_key: CM-4
  control_name: SECURITY IMPACT ANALYSIS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      Security impact analysis is conducted and documented within the Change
      Request (CR) process described in CM-3(b). All proposed configuration-
      controlled changes to the application are tested first in a sandboxed
      development environment before being pushed to a staging environment to
      be tested by another developer and by the Engineering team prior to final
      approval from CCB to move changes to the production environment.
  implementation_status: {{status.CM_4.contractor}}
  summary: >
    {{contractor.name_short}} tests and validates changes to the system before
    implementing the changes in production.
- control_key: CM-6
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: b
    text: >
      {{contractor.name_short}} developers follow security best practices
      according to the guidelines set by the {{contractor.name_short}} Security
      Office.
  - key: d
    text: >
      All changes to the configuration settings are logged in the Git source
      code version control system, which records the identity of the developer
      who committed each change. Version control is enforced, with previous
      tagged code releases kept for rollback purposes.
  implementation_status: {{status.CM_6.contractor}}
- control_key: CM-10
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      Drupal is hosted on a LAMP platform (Linux, Apache, MySQL, and PHP). These are
      all compatible with the Free Software Foundation's General Public License (GPL)
      version 2 or later and are freely available for use under copyright law.
  implementation_status: {{status.CM_10.contractor}}
- control_key: CM-11
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      All software installed in the system environment must be first approved
      via the CCB resulting in a Change Request (CR) being initiated and
      executed. Software installation on the computing nodes within the
      authorization boundary is restricted to administrators. All
      {{contractor.name_short}} internal administrators are informed of this
      during their initial training and as part of the rules of behavior
      document.
  - key: b
    text: >
      {{contractor.name_short}} enforces software installation policies through
      required acknowledgment and sign-off on acceptable use policy by
      {{contractor.name_short}} personnel. {{contractor.name_short}}
      Development is responsible for enforcing compliance with the acceptable
      use policy.
  - key: c
    text: >
      {{contractor.name_short}} monitors policy compliance continuously via
      the code release planning and quality control systems built into the
      System Development Life Cycle described in control SA-3.
  implementation_status: {{status.CM_11.contractor}}
  summary: >
    All software installed in the system environment must be first approved via
    the CCB resulting in a Change Request.
