family: CONFIGURATION MANAGEMENT
documentation_complete: false
satisfies:
- control_key: CM-1
  control_name: CONFIGURATION MANAGEMENT POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: |
      The system partially inherits this control from the FedRAMP Provisional ATO granted to the AWS Cloud Service Providers dated 1 May 2013.
    implementation_status: In Place
- control_key: CM-2
  control_name: BASELINE CONFIGURATION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      Hardware Baselines

      All hardware is maintained by AWS Cloud. The system therefore inherits hardware
      configuration aspects of this control from the FedRAMP Provisional ATO granted
      to the AWS Cloud dated 1 May 2013 for the following: baseline configuration.
    implementation_status: In Place
- control_key: CM-5
  control_name: ACCESS RESTRICTIONS FOR CHANGE
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud dated 1 May 2013 for the following: physical and logical
      access restrictions to server instances. Development and staging environments
      are logged by default as part of the AWS Cloud system.
    implementation_status: In Place
- control_key: CM-5 (1)
  control_name: AUTOMATED ACCESS ENFORCEMENT / AUDITING
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud dated 1 May 2013 for the following: automated access
      enforcement / access.
    implementation_status: In Place
- control_key: CM-6
  control_name: CONFIGURATION SETTINGS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud dated 1 May 2013 for the following: configuration settings.
    implementation_status: In Place
- control_key: CM-7
  control_name: LEAST FUNCTIONALITY
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud dated 1 May 2013 for the following: least functionality.
    implementation_status: In Place
- control_key: CM-8
  control_name: INFORMATION SYSTEM COMPONENT INVENTORY
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system inherits the platform software components of this control from the
      FedRAMP Provisional ATO granted to the AWS Cloud dated 1 May 2013 for the following:
      information system component inventory.
    implementation_status: In Place
- control_key: CM-8 (1)
  control_name: UPDATES DURING INSTALLATIONS / REMOVALS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      Website content is backed up daily by the AWS Managed Cloud hosting system,
      which is configured to take daily database snapshots

      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud dated 1 May 2013 for the following: components inventory
      updates.
    implementation_status: In Place
- control_key: CM-10
  control_name: SOFTWARE USAGE RESTRICTIONS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud Service Providers dated 1 May 2013 for the following:
      software usage restrictions.
    implementation_status: In Place
- control_key: CM-11
  control_name: USER-INSTALLED SOFTWARE
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Hybrid
  narrative:
  - key: a
    text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud Service Providers dated 1 May 2013 for the following:
      governing user installed software.
    implementation_status: In Place
  - key: b
    text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud Service Providers dated 1 May 2013 for the following:
      enforcing software installation policies.
    implementation_status: In Place
  - key: c
    text: >
      The system partially inherits this control from the FedRAMP Provisional ATO
      granted to the AWS Cloud Service Providers dated 1 May 2013 for the following:
      monitoring compliance.
    implementation_status: In Place
