family: PHYSICAL AND ENVIRONMENTAL PROTECTION
documentation_complete: false
satisfies:
- control_key: PE-1
  control_name: PHYSICAL AND ENVIRONMENTAL PROTECTION POLICY AND PROCEDURES
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-2
  control_name: PHYSICAL ACCESS AUTHORIZATIONS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-3
  control_name: PHYSICAL ACCESS CONTROL
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-6
  control_name: MONITORING PHYSICAL ACCESS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-8
  control_name: VISITOR ACCESS RECORDS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-12
  control_name: EMERGENCY LIGHTING
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-13
  control_name: FIRE PROTECTION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-14
  control_name: TEMPERATURE AND HUMIDITY CONTROLS
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-15
  control_name: WATER DAMAGE PROTECTION
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
- control_key: PE-16
  control_name: DELIVERY AND REMOVAL
  standard_key: NIST SP 800-53 Revision 4
  covered_by: []
  security_control_type: Inherited
  narrative:
  - text: >
      This Physical Environment control associated with hardware components within AWS is
      generally either partially or fully inherited from the AWS physical infrastructure,
      while the customer organization is responsible for any part of the control that is
      applicable to customer-controlled equipment and facilities, and the customer's
      configurable portion of the AWS logical infrastructure, including the Operating systems
      on Amazon EC2 instances and the customer's applications.


      For the U.S. East, U.S. West, and GovCloud regions, this control is inherited from
      pre-existing Agency Authority to Operate (ATO) or JAB provisional Authority to Operate
      under the Federal Risk and Authorization Management Program (FedRAMP).


      Refer to the AWS FedRAMP SSP artifacts, including the Control Implementation Summary
      and Customer Responsibility Matrix, available from the AWS Compliance Team.
      <https://aws.amazon.com/compliance/fedramp/>
  implementation_status: complete
