# This work is dual-licensed under Creative Commons Zero v1.0 Universal and GNU General Public License v3.0 or later.
# The file containts example code. Replace the values with information that is pertinent to your project.
name: The Project
name_short: Project
contact_email: TheProject@example.net
description:
client_name: The Client
client_name_short: Client
incident_response_plan_url: https://civicactions-handbook.readthedocs.io/en/latest/09-security/incident-response-plan
contingency_plan_url: https://civicactions-handbook.readthedocs.io/en/latest/09-security/contingency-plan
acceptable_use_policy_url: https://civicactions-handbook.readthedocs.io/en/latest/03-policies/security/#acceptable-use-policy
contact_sheet_url:
git_repository: https://github.com
backup_url: https://cpm.project.com/signin/
escalation_mail: TheProject@example.com
slack_link:
slack_channel:
slack_url:
contact_sheet:
issue_system: JIRA ticket
issue_system_url: '[JIRA ticket management system](https://project.atlassian.net/secure/)'
issue_incident: '[JIRA Incident ticket](https://project.atlassian.net/issues/?jql=issuetype=Incident)'
pager: OpsGenie
escalation_mail: TheProject@example.com
backup_snaps: '[CPM snapshots](https://cpm.project.com/)'
info_security_policy:
info_security_policy_url: https://obamawhitehouse.archives.gov/blog/2016/07/26/managing-federal-information-strategic-resource
info_security_policy_agency: OMB
video_urls:
  - https://zoom.us
  - https://chat.google.com/
