# This work is dual-licensed under Creative Commons Zero v1.0 Universal and GNU General Public License v3.0 or later.
# The file contains example code. Replace the values with information that is pertinent to your project.
name: Project Full Name
name_short: Project
contact_email: TheProject@example.net
description:
client_name: Client Full Name
client_name_short: Client
ssp_url: https://guidebook.civicactions.com/en/latest/common-practices-tools/security/incidents/
incident_response_plan_url: https://guidebook.civicactions.com/en/latest/common-practices-tools/security/incident-response-plan/
contingency_plan_url: https://guidebook.civicactions.com/en/latest/common-practices-tools/security/contingency-plan/
acceptable_use_policy_url: https://guidebook.civicactions.com/en/latest/company-policies/security/#acceptable-use-policy
git_repository: https://github.com/CivicActions/ssp-toolkit
slack_link:
slack_channel:
slack_url:
contact_sheet:
  name:
  url:
  image:
    path:
    alt:
issue_system: JIRA ticket
issue_system_url: '[JIRA ticket management system](https://project.atlassian.net/secure/)'
issue_incident: '[JIRA Incident ticket](https://project.atlassian.net/issues/?jql=issuetype=Incident)'
pager: OpsGenie
escalation_mail: TheProject@example.com
backup_snaps: backup snapshots
backup_system: Cloud Protection Manager (CPM) or other backup system
backup_url: https://cpm.project.com/signin/
backup_region:
  name: AWS US-WEST
  url: https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1
info_security_policy:
info_security_policy_url: https://obamawhitehouse.archives.gov/blog/2016/07/26/managing-federal-information-strategic-resource
info_security_policy_agency: OMB
video_urls:
  - https://zoom.us
  - https://chat.google.com/
